### ISSUE TITLE
Game crashes on start up 

### ISSUE THREAD

**Issue by landonh08** [isXander/better-particles#2]
When I put this mod in my mods folder the game crashes and says:                                                                                                  
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: net/minecraft/client/particle/EntityFX
Exit Code: -1

**Comment by isXander** [comment]
This mod is no longer supported. Please use my new [Particle Mod](https://github.com/isXander/ParticlesEnhanced)
